### ISSUE TITLE
Move ".ipynb" to nbs folder

### ISSUE THREAD

**Issue by chho-work** [pete88b/nbdev_colab_helper#6]
Hi,

I found this error when I changed "nbs_path" in "setting.ini" file
"""
Change to, e.g. "nbs", to put your notebooks in nbs dir instead of repo root
nbs_path = nbs
doc_path = docs 
"""
Steps:
Created a nbs folder in my drive.
Moved "00_core.ipynb" to "nbs" folder.  notebook2scripts() worked fine.
Left "index.ipynb" in the root folder.

This error message appeared when I tried to execute "nbdev_build_docs()":
![Screenshot from 2021-01-21 12-22-40](https://user-images.githubusercontent.com/58581036/105279931-9fb3da00-5be3-11eb-84b9-74c047171a12.png)

Then moved "index.ipynb" to "nbs" folder.  The same error message appeared!  

Please let me know what I am doing wrong!  Many thanks!

**Comment by pete88b** [comment]
Hi,

Think you can fix this by adding a simlink in the notebook folder. [From the nbdev tutorial](https://nbdev.fast.ai/tutorial.html#Note-if-using-a-subdirectory-to-contain-.ipynb-files-instead-of-the-project-root):

Note if using a subdirectory to contain .ipynb files instead of the project root

If you have set the parameter nbs_path to be anything other than the project root, you will not be able to import your generated modules without an extra step:

- either install these modules locally, as their relative import will take you beyond the top-level package, which can be done by running pip install -e . in the project root, to install the modules to your environment in editable mode.
- or make a simlink in your notebook folder to the library folder, which can be done by running ln -s lib_path lib_name (adjust lib_path and lib_name to your use case).

**Comment by chho-work** [comment]
Hi,
Thanks for your response!  I think the problem can be solved if I move up one level.  

Details:
1) index.ipynb, 00_core.ipynb, and any other .ipynb must be in nbs folder.
2) Before executing the command nbdev_build_docs(), I changed my directory and moved up one level.
from "/github/syntheticReplica/nbs" to "/github/syntheticReplica"  and then executed nbdev_build_docs().  The error disappeared!

I did the experiment using my local computer and it worked!  I believe it should be the same for Colab!

Thanks and have a good day!
